<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="com.aventstack.chaintest.plugins.ChainTestListener"/>
    <listener class-name="listeners.MyTestNGListener"/>
    <listener class-name="listeners.RetryTransformer"/>
  </listeners>
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="testcases.loginApplication">
        <methods>
          <include name="tearDown"/>
          <include name="setup"/>
          <include name="loginWithValidCredenatials" invocation-numbers="0"/>
        </methods>
      </class> <!-- testcases.loginApplication -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
